### ISSUE TITLE
how to add myself encoder( h264)

### ISSUE THREAD

**Issue by xiangxud** [pion/mediadevices#328]
how to add myself encoder( h264) and use for pion webrtc

**Comment by lherman-cs** [comment]
@xiangxud since specific codec implementations are not coupled to mediadevices, you can achieve this by registering your [VideoEncoderBuilder](https://pkg.go.dev/github.com/pion/mediadevices@v0.2.0/pkg/codec#VideoEncoderBuilder) implementation using [WithVideoEncoders](https://pkg.go.dev/github.com/pion/mediadevices#WithVideoEncoders) API.

I would highly suggest taking a look at one of the codec implementations in the [codec folder](https://github.com/pion/mediadevices/tree/master/pkg/codec) as a reference.

**Comment by xiangxud** [comment]
thanks ,i will try it
